services:
  - type: web
    name: deno-proxy-visualizer
    env: deno
    plan: free
    region: oregon # or another region of your choice
    branch: main
    buildFilter:
      paths:
      - "visualizer_app_v2/**"
    build_command: "deno cache main.ts"
    start_command: "deno run --allow-net --allow-read --allow-env main.ts"